version: '3.8'

services:
  web:
    build: .
    ports:
      - "8443:443" # HTTPS
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: surbhi@postgres
      POSTGRES_DB: money_transfer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./money_transfer.sql:/docker-entrypoint-initdb.d/money_transfer.sql

volumes:
  db_data: